### ISSUE TITLE
Add tqdm to second-phase (mix) 

### ISSUE THREAD

**Issue by jeffwright13** [jeffwright13/audio_program_generator#14]
The mix() step can take a while if the mixfile is large (>10MB on my Macboox Pro). Would be nice to implement a second-phase progress bar for this step. 

Implementation unknown at this time, since tqdm simply wraps an iterable, and the mix() function is only called once (not line by line when processing input text file, as in first phase).

**Comment by jeffwright13** [comment]
This is probably not possible since tqdm needs an iterable over which to loop, and there is one call to mix(). Currently have worded my way around it in the apg.py helper docstring.

**Comment by bbelderbos** [comment]
Yep had to listify mine :) 
https://github.com/PyBites-Open-Source/git-stats/commit/ad7c1547a986f9a7ed1a390516bc7294ec701ea6

**Comment by jeffwright13** [comment]
May possibly be worked around if CLI is re-implemented in `typer`.

**Comment by jeffwright13** [comment]
Closing per new issue 47.
