### ISSUE TITLE
Update README with more explicit build instructions, esp. around PyObjC

### ISSUE THREAD

**Issue by jeffwright13** [jeffwright13/audio_program_generator#2]
Need more explicit build instructions for users of (mac, linux, windows).
For mac: requires "pip3 install PyObjC".

See: 
https://stackoverflow.com/questions/29222269/is-there-a-way-to-have-a-conditional-requirements-txt-file-for-my-python-applica/35614580#35614580
https://www.python.org/dev/peps/pep-0508/

**Comment by bbelderbos** [comment]
Haha I hit the same issue for this project on Mac: https://github.com/pybites/pbalarm/blob/main/pyproject.toml

**Comment by jeffwright13** [comment]
I am actually not gonna get into the business of coaching users how to install FFMPEG. This is listed as a pre-req in the README. Good enough.

**Comment by bbelderbos** [comment]
Yep, for me (Mac) it was just a `brew install` away :)
