### ISSUE TITLE
Enhancement: 'book mode'

### ISSUE THREAD

**Issue by jeffwright13** [jeffwright13/audio_program_generator#27]
What happens if someone wants to generate an audio book? They should be able to just copy/paste the text of the book into a phrase file (without having to specify the semicolon or durations). Need to experiement and see what happens with long lines; paragrpahs; etc.

**Comment by bbelderbos** [comment]
Good point, would be nice if the app can handle a bunch of lines without durations and handles it in a sensible way.

**Comment by jeffwright13** [comment]
Rudimentary implementation in 1.7.1.0.
