### ISSUE TITLE
Enhancement: make APG a 'black box'

### ISSUE THREAD

**Issue by jeffwright13** [jeffwright13/audio_program_generator#4]
@bbelderbos pointed out that with the current implementation of apg, there is a lot of external code required that first submits a text file, then takes back raw audiosegments (from `gen_speech()`) and then turns around and resubmits them back into apg (into `mix()`). This could all be internalized such that the only call to apg takes in the text file and then returns the processed/mixed file.

**Comment by bbelderbos** [comment]
Yes correct, there was code in the Flask view I think you can and should move into the apg class.

**Comment by jeffwright13** [comment]
Done
