### ISSUE TITLE
Enhancements (per Bob)

### ISSUE THREAD

**Issue by jeffwright13** [jeffwright13/audio_program_generator#8]
- [x] Rename Apg claas to AudioProgramgenerator (from [Bob's suggestion](https://github.com/jeffwright13/apg_flask/pull/2/files/add6ea18a2e85c29524238c86c350d2dc10bc1a2#r644984758) in apg_flask). This will require rework in apg's main() as well as in apg_flask's views.py 
- [x] Rename gen_speech method to _gen_speech, since it is entirely internal.
- [x] Change "if self.to_mix == True:" to "if self.to_mix:".

- [x] Per [this comment](https://github.com/jeffwright13/apg_flask/pull/2/files/add6ea18a2e85c29524238c86c350d2dc10bc1a2#r644993848), this code in apg_flask's "views.py:
```
# Verify phrase_file type is allowed; if not, redirect to input form.
if (
    Path(req_phrase_file_obj.filename).suffix
    not in app.config["PHRASEFILE_EXTENSIONS"]
):
    return render_template("public/setvals.html")
```

could be refactored ... "These can be methods on the apg class so you don't have to use flask sessions to pass around this apg related data. So I would make apg instance higher up and do something like:"

```
file_ext = Path(req_phrase_file_obj.filename).suffix
if not apg.is_valid_extension(file_ext):
    render...
```

- [x] Per [this comment](https://github.com/jeffwright13/apg_flask/pull/2#discussion_r645378277), consider moving file-extension code into the class so surrounding code doesn't have to do that validation.

**Comment by bbelderbos** [comment]
yep cool

**Comment by jeffwright13** [comment]
Code was added in branch issue8-filename-validation, and then merged to main. New version 1.8.0.0 is now pushed to Pypi. 
Unfortunately, this [breaks apg-flask](https://github.com/jeffwright13/apg_flask/issues/27). Will need to investigate.

**Comment by jeffwright13** [comment]
Filetype checking code was removed. After a lot of investigation, I decided to push the responsibility of making sure the filetype is correct back onto the calling code (CLI or GUI). APG as a class expects an object that has a read() method so that it can extract the text to process. It makes no sense to force it to check that the file that gave it that object matchese ".txt" or ".wav."
